base_url = "https://archjh.github.io"
compile_sass = true
title = "Archjh Blog's"
description = "A robust, elegant dark theme"
generate_feeds = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true 

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "one-dark"

[search]
index_format = "elasticlunr_json"

[extra]
author = "John Doe"
after_dark_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
after_dark_title = "Archjh Blog's"

# Nicer codeblocks with copy to clipboard 
codeblock = true

# Enable MathJax support
latex = true

# Enable search bar 
enable_search = true 

[extra]
latex = true
